### ISSUE TITLE
DD_SERVICE and DD_ENV enviroment variables not getting created

### ISSUE THREAD

**Issue by joshuabaird** [DataDog/datadog-lambda-extension#113]
The [docs](https://docs.datadoghq.com/serverless/libraries_integrations/macro/) state that the `DD_SERVICE` and `DD_ENV` environment variables will be created on the Lambda function _if_ `service` and `env` are configured on the transform.  Using the latest version (v67) -- we are not seeing this behavior.

Environment variables are *not* being created, but tags are.  

Here is our transform:

```
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      pythonLayerVersion: 67
      extensionLayerVersion: 36
      site: "datadoghq.com"
      apiKey: !Ref DatadogAPIKey
      env: staging
      service: my-awesome-service
```
