### ISSUE TITLE
Sending logs, metrics or traces to Vector

### ISSUE THREAD

**Issue by barryib** [DataDog/datadog-lambda-extension#174]
Actually we can easily configure Datadog agent to send logs, metrics or traces to a vector aggregator. But seems it doesn't work for the lambda extension.

Used both bellow configurations, but the datadog extension keep sending log to the datadog intake directly.

```yaml
vector:
  logs:
    enabled: true
    url: "http://<OPW_HOST>:8282"
```

```shell
DD_VECTOR_LOGS_ENABLED="true"
DD_VECTOR_LOGS_URL="http://<OPW_HOST>:8282"
```

Do you know if there is a plan to fix this or anyone can direct me where/how to fix ?

Thanks
