### ISSUE TITLE
Extension adds significant execution overhead 

### ISSUE THREAD

**Issue by mrworkman** [DataDog/datadog-lambda-extension#181]
This is on AWS Lambda, Python 3.9, with extension version 83 on ARM64.

![image](https://github.com/DataDog/datadog-lambda-extension/assets/20093062/d146863c-020c-4118-a54d-777025ef5e6d)

According to the extension's description, it's supposed to ship logs asynchronously, but it appears to be doing so _synchronously_. Setting `DD_SERVERLESS_FLUSH_STRATEGY=periodically,60000` only defers the latency -- most executions go down to around 50ms, but every minute or so, they spike to ~1000ms, which is not ideal.

### Extension Enabled

![image](https://github.com/DataDog/datadog-lambda-extension/assets/20093062/7002f654-8c65-4cad-9381-024e79a1ee2d)

### Extension Disabled, with DD_FLUSH_TO_LOG=true

![image](https://github.com/DataDog/datadog-lambda-extension/assets/20093062/3814e87a-4098-4058-b65a-71f9b1c30615)

As you can see, the difference is an order of magnitude.

Is this expected/normal?

**Comment by astuyve** [comment]
Hi @mrworkman - thanks for reaching out!

When using Lambda extensions, work performed by extensions _after_ the lambda function handler exits and returns to the caller is *still counted* in the duration metric.

So what you're seeing both here and with `DD_SERVERLESS_FLUSH_STRATEGY=periodically,60000` is expected, but happening _after_ the function execution completes and *not* impacting the response time of your Lambda function.

This is why we provide the `runtime_duration` enhanced metric, although overall we always recommend tracking end to end latency (using something like RUM or api gateway quantile metrics, for example)

We document this in full [here](https://docs.datadoghq.com/serverless/libraries_integrations/extension/#overhead) and there's a nice AWS blog post which [also covers this](https://aws.amazon.com/blogs/compute/performance-and-functionality-improvements-for-aws-lambda-extensions/).

I hope I've helped!

**Comment by mrworkman** [comment]
So, to add more to this, we discovered this issue where we have one lambda synchronously invoking others. So, the first one has to wait for the others to finish before it can proceed. 

You can see an example in the following trace. One lambda invokes the other, and has to wait 776ms for the request to complete.

![image](https://github.com/DataDog/datadog-lambda-extension/assets/20093062/332394c3-e984-4fa8-83ca-d36776085067)

When removing the DD Extension, this drops considerably (in this case, to 94ms), and the overall request takes that much less time.

![image](https://github.com/DataDog/datadog-lambda-extension/assets/20093062/6c5e0065-03f9-43c6-b33a-b35c9c38165a)

**Comment by astuyve** [comment]
Okay great, thanks for the context  – that's super helpful!

I'm at re:Invent this week but have asked someone else to investigate this, although it may be fastest to open a bug ticket with us; you can email support@datadoghq.com to kick that off. Feel free to include this report in the bug ticket.

Thanks!

**Comment by mrworkman** [comment]
For reference, the support ticket is 1453840.

**Comment by astuyve** [comment]
Hey folks!

I just wanted to follow up in public quickly, as we're still figuring things out via support.

I'm having trouble reproducing this with the same parameters (py3.9-arm, 1024mb RAM, deployed to eu-west-1, pushing telemetry to datadog in US1, datadog extension v51 and datadog-lambda-python v85).

I've created two functions, both are identical and create some logs, and a custom metric. One function utilizes the default flush strategy, the other configures `DD_SERVERLESS_FLUSH_STRATEGY=periodically,60000`, as per this thread.

Then I created an `invoker` function which synchronously invokes each function (using API Gateway), and measures the end to end response time. To make this easier to reproduce, I both create these as a custom metric and emit them as structured logs.

Regardless of the flush strategy, the max RTT latency is about 50-60ms during a warm start:
![image](https://github.com/DataDog/datadog-lambda-extension/assets/1598537/f6e804fe-25a2-4948-8a10-a56f7f0d5c80)

Function code:
```python
import json
import requests
import os
import time

from datadog_lambda.metric import lambda_metric


def hello(event, context):
    body = {
        "message": "function executed successfully!",
    }
    print('Creating a custom metric!')
    lambda_metric(
        "rtt_latency.custom_metric_created",
        1,
        tags=[]
    )
    print('we did it, time to return')
    response = {
        "statusCode": 200,
        "body": json.dumps(body)
    }

    return response


def invoke(event, context):
    base_url = os.getenv('BASE_URL')
    baseline_start = time.time_ns()
    requests.get(f'{base_url}/baseline')
    baseline_end = time.time_ns()
    requests.get(f'{base_url}/periodic')
    periodic_end = time.time_ns()

    baseline_duration = (baseline_end - baseline_start) // 1_000_000
    periodic_duration = (periodic_end - baseline_end) // 1_000_000
    print(f'{{baseline_duration: {baseline_duration}}}')
    print(f'{{periodic_duration: {periodic_duration}}}')
    lambda_metric(
        "rtt_latency.baseline",
        baseline_duration,
        tags=[]
    )
    lambda_metric(
        "rtt_latency.periodic",
        periodic_duration,
        tags=[]
    )
 ```
 
 `serverless.yml`
 ```yml
 service: py39-cross-region-demo
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  region: eu-west-1

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

functions:
  baselineDefaultFlush:
    handler: handler.hello
    events:
      - httpApi:
          method: get
          path: /baseline
  periodicFlush:
    handler: handler.hello
    environment:
      DD_SERVERLESS_FLUSH_STRATEGY: periodically,60000
    events:
      - httpApi:
          method: get
          path: /periodic
  invoker:
    handler: handler.invoke
    environment:
      BASE_URL: !GetAtt HttpApi.ApiEndpoint
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-plugin-datadog
  ```

My hypotheses are limited as I'd expect any tracing-based latency to also exist with the datadog lambda forwarder configuration (which you've mentioned seems to remediate this issue entirely).

I'm looking forward to our discussion later this week,
Thanks!
