### ISSUE TITLE
Support SSM Parameter Store secure string for the DD_AP_KEY

### ISSUE THREAD

**Issue by roimor** [DataDog/datadog-lambda-extension#23]
hey , whats the whole purpose of this project if it cannot be secured properly ?

```
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKey: <DATADOG_API_KEY>
      pythonLayerVersion: 47
      extensionLayerVersion: 10
      service: "<SERVICE>" # Optional
      env: "<ENV>" # Optional
```

we have to be able to resolve the apiKey from somewhere...
