### ISSUE TITLE
false WARN messages after extension upgrade

### ISSUE THREAD

**Issue by Vladikamira** [DataDog/datadog-lambda-extension#393]
Hi, as I mentioned [here](https://github.com/DataDog/datadog-lambda-extension/issues/195#issuecomment-2343986398) after an upgrade the datadog lambda extension to version `v64` we got weird messages popped up in the logs
```
2024-09-11 15:09:38 UTC | DD_EXTENSION | WARN | config key flare_stripped_keys is unknown
2024-09-11 15:09:38 UTC | DD_EXTENSION | WARN | failed to get configuration value for key "flare_stripped_keys": unable to cast <nil> of type <nil> to []string
2024-09-11 15:09:38 UTC | DD_EXTENSION | WARN | config key scrubber.additional_keys is unknown
2024-09-11 15:09:38 UTC | DD_EXTENSION | WARN | failed to get configuration value for key "scrubber.additional_keys": unable to cast <nil> of type <nil> to []string
```
we don't have any of these configurations configured, therefore I assume it's a bug

here is our config:
```
apm_config:
  enabled: true

site: datadoghq.eu

use_dogstatsd: false

cloud_provider_metadata:
  - "aws"

# https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host
otlp_config:
  receiver:
    protocols:
      grpc:
        endpoint: 127.0.0.1:50052
  metrics:
    enabled: true
    resource_attributes_as_tags: true
    tag_cardinality: low
  traces:
    enabled: true
    span_name_remappings:
      go.opentelemetry.io_contrib_instrumentation_google.golang.org_grpc_otelgrpc.server: grpc.server
      go.opentelemetry.io_contrib_instrumentation_google.golang.org_grpc_otelgrpc.client: grpc.client
      go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp.client: http.client
      go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp.server: http.server
      observability_lambda.server: aws.lambda
      aws.lambda.internal: aws.lambda

logs_enabled: true
logs_config:
  processing_rules:
    - type: exclude_at_match
      name: exclude_start_and_end_logs
      pattern: (START|END|REPORT)\s
```

I did tried to add empty list to the config
```
scrubber:
  additional_keys: []
```
but it didn't solve the problem
