### ISSUE TITLE
panic on invocation after upgrade to v66

### ISSUE THREAD

**Issue by Vladikamira** [DataDog/datadog-lambda-extension#487]
After upgrading to `v66` as a fix for my [previous issue](https://github.com/DataDog/datadog-lambda-extension/issues/393) (which has been resolved it seems in there) I see a panic in the extension on invocation:

a panic
```
tine 193 [running]:
github.com/DataDog/datadog-agent/comp/otelcol/otlp.(*tagEnricher).Enrich(0xc0009882b8, {0x0?, 0x0?}, {0x0, 0x0, 0x41d7e5?}, 0xc0007b0600)
/tmp/dd/datadog-agent/comp/otelcol/otlp/collector.go:77 +0x18a
github.com/DataDog/datadog-agent/comp/otelcol/otlp/components/exporter/serializerexporter.(*serializerConsumer).ConsumeTimeSeries(0xc000244000, {0x1efd348?, 0xc000408000?}, 0xc0007b0600, 0x1, 0x180c265fa408cf44, 0x3ff0000000000000)
/tmp/dd/datadog-agent/comp/otelcol/otlp/components/exporter/serializerexporter/consumer.go:78 +0x91
github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics.(*Translator).mapNumberMetrics(0xc000478000, {0x1efd348, 0xc000408000}, {0x7f9c188596e0, 0xc000244000}, 0xc00090b8d0, 0x1, {0xc0009b7f60?, 0xc0001cecc4?})
/root/go/pkg/mod/github.com/!data!dog/opentelemetry-mapping-go/pkg/otlp/metrics@v0.21.0/metrics_translator.go:172 +0x208
github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics.(*Translator).mapToDDFormat(0xc000478000, {0x1efd348, 0xc000408000}, {0xc0008179e0?, 0xc0001cecc4?}, {0x1ef4728, 0xc000244000}, {0xc000408120, 0x3, 0x3}, ...)
/root/go/pkg/mod/github.com/!data!dog/opentelemetry-mapping-go/pkg/otlp/metrics@v0.21.0/metrics_translator.go:852 +0x1187
github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics.(*Translator).MapMetrics(0xc000478000, {0x1efd348, 0xc000408000}, {0xc000012cd8?, 0xc0001cecc4?}, {0x1ef4728, 0xc000244000})
/root/go/pkg/mod/github.com/!data!dog/opentelemetry-mapping-go/pkg/otlp/metrics@v0.21.0/metrics_translator.go:813 +0xb54
github.com/DataDog/datadog-agent/comp/otelcol/otlp/components/exporter/serializerexporter.(*Exporter).ConsumeMetrics(0xc0003ea4e0, {0x1efd348, 0xc000408000}, {0xc000012cd8?, 0xc0001cecc4?})
/tmp/dd/datadog-agent/comp/otelcol/otlp/components/exporter/serializerexporter/exporter.go:177 +0x105
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).Export(0x0?, {0x1efd348?, 0xc000408000?})
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/exporterhelper/metrics.go:61 +0x31
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*TimeoutSender).Send(0xc00097c000?, {0x1efd348?, 0xc000408000?}, {0x1efebc8?, 0xc000012d80?})
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/exporterhelper/internal/timeout_sender.go:45 +0x48
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseRequestSender).Send(0xc000733540?, {0x1efd348?, 0xc000408000?}, {0x1efebc8?, 0xc000012d80?})
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/exporterhelper/internal/request_sender.go:28 +0x30
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).Send(0xc0006665d0, {0x1efd3b8?, 0xc000940f50?}, {0x1efebc8, 0xc000012d80})
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/exporterhelper/metrics.go:166 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseRequestSender).Send(0xc0005cf700?, {0x1efd3b8?, 0xc000940f50?}, {0x1efebc8?, 0xc000012d80?})
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/exporterhelper/internal/request_sender.go:28 +0x30
go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1({0x1efd3b8?, 0xc000940f50?}, {0x1efebc8, 0xc000012d80})
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/exporterhelper/internal/queue_sender.go:90 +0x7d
go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1()
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/internal/queue/consumers.go:43 +0x85
created by go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start in goroutine 50
/root/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.113.0/internal/queue/consumers.go:35 +0x45
RequestId: 81be89da-0716-44e3-8110-e2a4211147f3 Error: exit status 2
Extension.Crash
END RequestId: 81be89da-0716-44e3-8110-e2a4211147f3
REPORT RequestId: 81be89da-0716-44e3-8110-e2a4211147f3	Duration: 163.21 ms	Billed Duration: 4973 ms	Memory Size: 192 MB	Max Memory Used: 105 MB	Init Duration: 4809.67 ms	

```

config:
```yaml
apm_config:
  enabled: true

site: datadoghq.eu

use_dogstatsd: false

cloud_provider_metadata:
  - "aws"

# https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host
otlp_config:
  receiver:
    protocols:
      grpc:
        endpoint: 127.0.0.1:50052
  metrics:
    enabled: true
    resource_attributes_as_tags: true
    tag_cardinality: low
  traces:
    enabled: true
    span_name_remappings:
      go.opentelemetry.io_contrib_instrumentation_google.golang.org_grpc_otelgrpc.server: grpc.server
      go.opentelemetry.io_contrib_instrumentation_google.golang.org_grpc_otelgrpc.client: grpc.client
      go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp.client: http.client
      go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp.server: http.server
      observability_lambda.server: aws.lambda
      aws.lambda.internal: aws.lambda

logs_enabled: true
logs_config:
  processing_rules:
    - type: exclude_at_match
      name: exclude_start_and_end_logs
      pattern: (START|END|REPORT)\s
```
